name: 'Edit .net core database connection string in appsettings.json'
description: 'Edit a connection string for .NET Core in appsettings.json'
author: 'Benjamin Day Consulting, Inc.'
inputs:
  name:
    required: true
    description: 'name of the connection string'
    default: 'default'
  connectionString:
    required: true
    description: 'value for the connection string'
    default: ''
  pathToSettingsFile:
    required: true
    description: 'path to your appsettings.json file'
    default: 'appsettings.json'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'database'
  color: 'blue'
